package net.obsearch.example.bio;

import hep.aida.bin.StaticBin1D;
import net.obsearch.example.lev.OBString;
import net.obsearch.example.protein.MyDistance;
import net.obsearch.exception.OBException;

import org.junit.Test;

public class TestCheapStringDistance {

	@Test
	public void test1() throws OBException {
		String a = "MITVNVDLGERAYPIHIGADLIGRTELFAPHIAGASVTIVTNTTVEPLYGDTLRAALAPLGKRVSTVVLPDGEAYKNWETLNLIFDGLLEQHADRKTTLIALGGGVIGDMTGFAAACYMRGVPFIQVPTTLLSQVDSSVGGKTGINHPLGKNMIGAFYQPQAVIADIGALSTLPDRELAAGVAEIVKTGAIADAAFFDWIEANVGALTRRDPDALAHAVKRSCEIKAGVVAADEREGGLRAILNFGHTFGHAIEAGLGYGEWLHGEAVGCGMVMAADLSVRTGHLDEASRARLCRVVEAAHLPTRAPDLGDARYVELMRVDKKAEAGAIKFILLKRFGETIITPAPDDAVLATLAATTR";
		String b = "MITVNVDLGERAYPIHIGADLIGRTELFAPHIAGASVTIVTNTTVEPLYGDTLRAALAPLGKRSTVVLPDGEAYKNWETLNLIFDGLLEQHADRKTTLIALGGGVIGDMTGFAAACYMRGVPFIQVPTTLLSQVDSSVGGKTGINHPLGKNMIGAFYQPQAVIADIGALSTLPDRELAAGVAEIVKTGAIADAAFFDWIEANVGALTRRDPDALAHAVKRSCEIKAGVVAADEREGGLRAILNFGHTFGHAIEAGLGYGEWLHGEAVGCGMVMAADLSVRTGHLDEASRARLCRVVEAAHLPTRAPDLGDARYVELMRVDKKAEAGAIKFILLKRFGETIITPAPDDAVLATLAATTR";
		String c = "MITVNVDLGDRAYPIHIGAGLIGRTELFAPHIKGSSVTIVTNTTVDPLYGDALRAALAPLGKRVSTVVLPDGEAYKNWETLNLIFDGLLTDHADRKTTLVALGGGVVGDMTGFAAACYMRGVPFIQVPTTLLSQVDSSVGGKTGINHPLGKNMIGAFYQPQAVIADIGALTTLPDRELAAGVAEVIKTGAIADAGFFDWIEANVEALNRREPAALAHAVKRSCEIKASVVAADEREGGLRAILNFGHTFGHAIEAGLGYGEWLHGEAVGCGMVMAGDLSVRLGLLDEASRQRLDAVIAAAHLPTRGPALGDARYMDLMRVDKKAEAGAIKFILLKRFGDTLITQAPDEAVFATLAQTTR";
		MyDistance ad = new MyDistance("a", a);
		MyDistance bd = new MyDistance("b", b);
		OBString al = new OBString(a);
		OBString bl = new OBString(c);
		System.out.print("MyD" + ad.distance(bd) + "\n");
		System.out.print("lev" + al.distance(bl) + "\n");
		int i = 0;
		StaticBin1D s = new StaticBin1D();
		int res = 0;
		while (i < 20000) {
			
				long time = System.currentTimeMillis();
				res += al.distance(bl);
				// res+= ad.distance(bd);
				if (i >= 10000) {
				s.add(System.currentTimeMillis() - time);
				}
		
			i++;
		}
		System.out.println("DO:" + s.toString());
	}

}
